---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
        
    - name: Copy the files to index destination folder.
         copy: >
          src=/tmp/dockeransiblejenkins/index1.html
          dest=/var/www/html/index1.html
          owner=root
          group=root
          mode=0644
    - name: Copy the style files to destination folder.
         copy: >
          src=/tmp/dockeransiblejenkins/style.css
          dest=/var/www/html/style.css
          owner=root
          group=root
          mode=0644
    - name: Copy the javascript files to destination folder.
         copy: >
          src=/tmp/dockeransiblejenkins/scorekeeper.js
          dest=/var/www/html/scorekeeper.js
          owner=root
          group=root
          mode=0644    
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "khurshid14/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
